// Mock Tesla Service for testing vehicle management interface
// This provides realistic Tesla API responses for development and testing

export const MockTeslaAPI = {
  // Mock vehicle data responses
  getVehicleData: (vehicleId: number) => {
    const mockData = {
      1234567890123: {
        // Test Model Y data
        id: 1234567890123,
        user_id: 123456,
        vehicle_id: 1234567890123,
        vin: '5YJYGDEE8MF123456',
        display_name: 'Test Model Y',
        option_codes: 'AD15,MDL3,PBSB,RENA,BT37,ID3W,RF3G,S3PB,DRLH,DV2W,W39B,APF0,COUS,BC3B,CH07,PC30,FC3P,FG31,GLFR,HL31,HM31,IL31,LTPB,MR31,FM3B,RS3H,SA3P,STCP,SC04,SU3C,T3CA,TW00,TM00,UT3P,WR00,AU3P,APH3,AF00,ZCST,MI00,CDM0',
        color: 'Pearl White Multi-Coat',
        access_type: 'OWNER',
        granular_access: { hide_private: false },
        tokens: ['1234567890123'],
        state: 'online',
        in_service: false,
        id_s: '1234567890123',
        calendar_enabled: true,
        api_version: 42,
        backseat_token: null,
        backseat_token_updated_at: null,
        ble_autopair_enrolled: false,
        command_signing: 'allowed',
        
        // Detailed vehicle data
        charge_state: {
          battery_heater_on: false,
          battery_level: 82,
          battery_range: 279.12,
          charge_amps: 48,
          charge_current_request: 48,
          charge_current_request_max: 48,
          charge_enable_request: true,
          charge_energy_added: 14.85,
          charge_limit_soc: 90,
          charge_limit_soc_max: 100,
          charge_limit_soc_min: 50,
          charge_limit_soc_std: 90,
          charge_miles_added_ideal: 60.0,
          charge_miles_added_rated: 60.0,
          charge_port_cold_weather_mode: false,
          charge_port_color: '<invalid>',
          charge_port_door_open: false,
          charge_port_latch: 'Engaged',
          charge_rate: 0.0,
          charger_actual_current: 0,
          charger_pilot_current: 48,
          charger_power: 0,
          charger_voltage: 2,
          charging_state: 'Complete',
          conn_charge_cable: '<invalid>',
          est_battery_range: 237.86,
          fast_charger_brand: '<invalid>',
          fast_charger_present: false,
          fast_charger_type: '<invalid>',
          ideal_battery_range: 279.12,
          managed_charging_active: false,
          managed_charging_start_time: null,
          managed_charging_user_canceled: false,
          max_range_charge_counter: 0,
          minutes_to_full_charge: 0,
          not_enough_power_to_heat: false,
          off_peak_charging_enabled: false,
          off_peak_charging_times: 'all_week',
          off_peak_hours_end_time: 360,
          preconditioning_enabled: false,
          preconditioning_times: 'all_week',
          scheduled_charging_mode: 'Off',
          scheduled_charging_pending: false,
          scheduled_charging_start_time: null,
          scheduled_departure_time: 1640995200,
          supercharger_session_trip_planner: false,
          time_to_full_charge: 0.0,
          timestamp: Date.now(),
          trip_charging: false,
          usable_battery_level: 82,
          user_charge_enable_request: null
        },
        
        drive_state: {
          gps_as_of: Date.now(),
          heading: 45,
          latitude: 37.7749,
          longitude: -122.4194,
          native_latitude: 37.7749,
          native_longitude: -122.4194,
          native_location_supported: 1,
          native_type: 'wgs',
          power: 0,
          shift_state: 'P',
          speed: null,
          timestamp: Date.now()
        },
        
        vehicle_state: {
          api_version: 42,
          autopark_state_v3: 'ready',
          autopark_style: 'dead_man',
          calendar_supported: true,
          car_version: '2023.44.30.8',
          center_display_state: 0,
          dashcam_clip_save_available: true,
          dashcam_state: 'Unavailable',
          df: 0,
          dr: 0,
          fd_window: 0,
          feature_bitmask: '1ff3,0',
          fp_window: 0,
          ft: 0,
          homelink_device_count: 0,
          homelink_nearby: false,
          is_user_present: false,
          last_autopark_error: 'no_error',
          locked: true,
          media_state: { remote_control_enabled: true },
          notifications_supported: true,
          odometer: 15420.245618,
          parsed_calendar_supported: true,
          pf: 0,
          pr: 0,
          rd_window: 0,
          remote_start: false,
          remote_start_enabled: true,
          remote_start_supported: true,
          rp_window: 0,
          rt: 0,
          santa_mode: 0,
          sentry_mode: false,
          sentry_mode_available: true,
          smart_summon_available: true,
          software_update: {
            download_perc: 0,
            expected_duration_sec: 2700,
            install_perc: 0,
            status: '',
            version: ''
          },
          speed_limit_mode: {
            active: false,
            current_limit_mph: 75.0,
            max_limit_mph: 90,
            min_limit_mph: 50,
            pin_code_set: false
          },
          summon_standby_mode_enabled: false,
          timestamp: Date.now(),
          valet_mode: false,
          valet_pin_needed: true,
          vehicle_name: 'Test Model Y',
          webcam_available: true
        },
        
        vehicle_config: {
          aux_park_lamps: 'Eu',
          badge_version: 0,
          can_accept_navigation_requests: true,
          can_actuate_trunks: true,
          car_special_type: 'base',
          car_type: 'model3',
          charge_port_type: 'CCS',
          dashcam_clip_save_supported: true,
          default_charge_to_max: false,
          driver_assist: 'TeslaAP3',
          ece_restrictions: false,
          efficiency_package: 'MY2021',
          eu_vehicle: false,
          exterior_color: 'PearlWhite',
          exterior_trim: 'Black',
          exterior_trim_override: '',
          has_air_suspension: false,
          has_ludicrous_mode: false,
          has_seat_cooling: false,
          headlamp_type: 'Led',
          interior_trim_type: 'Black2',
          key_version: 1,
          motorized_charge_port: true,
          paint_color_override: '',
          performance_package: 'Base',
          plg: false,
          pws: false,
          rear_drive_unit: 'PM216MOSFET',
          rear_seat_heaters: 1,
          rear_seat_type: 0,
          rhd: false,
          roof_color: 'RoofColorGlass',
          seat_type: null,
          spoiler_type: 'None',
          sun_roof_installed: null,
          third_row_seats: 'None',
          timestamp: Date.now(),
          trim_badging: 'p74d',
          use_range_badging: true,
          utc_offset_seconds: -28800,
          webcam_selfie_supported: false,
          wheel_type: 'Apollo19'
        }
      },
      
      1234567890124: {
        // Test Model S data
        id: 1234567890124,
        user_id: 123456,
        vehicle_id: 1234567890124,
        vin: '5YJSA1E26JF987654',
        display_name: 'Test Model S',
        option_codes: 'MDLS,RENA,TM00,DRLH,PF00,BT37,ID3W,RF3G,S3PB,DRLH,DV2W,W39B,APF0,COUS,BC3R,CH07,PC30,FC3P,FG31,GLFR,HL31,HM31,IL31,LTPB,MR31,FM3U,RS3H,SA3P,STCP,SC04,SU3C,T3CA,TW01,TM00,UT3P,WR00,AU3P,APH4,AF00,ZCST,MI02,CDM0',
        color: 'Midnight Silver Metallic',
        access_type: 'OWNER',
        granular_access: { hide_private: false },
        tokens: ['1234567890124'],
        state: 'asleep',
        in_service: false,
        id_s: '1234567890124',
        calendar_enabled: true,
        api_version: 42,
        backseat_token: null,
        backseat_token_updated_at: null,
        ble_autopair_enrolled: false,
        command_signing: 'allowed',
        
        // Limited data for sleeping vehicle
        charge_state: {
          battery_level: 95,
          battery_range: 402.5,
          charging_state: 'Complete',
          charge_limit_soc: 90,
          usable_battery_level: 95,
          timestamp: Date.now()
        },
        
        vehicle_state: {
          car_version: '2023.44.30.8',
          locked: true,
          odometer: 28765.891234,
          sentry_mode: true,
          timestamp: Date.now()
        },
        
        vehicle_config: {
          car_type: 'models',
          exterior_color: 'MidnightSilver',
          wheel_type: 'Base19',
          trim_badging: 'p85d',
          performance_package: 'P1',
          timestamp: Date.now()
        }
      }
    };
    
    return mockData[vehicleId] || null;
  },
  
  // Mock vehicles list
  getVehicles: () => [
    {
      id: 1234567890123,
      user_id: 123456,
      vehicle_id: 1234567890123,
      vin: '5YJYGDEE8MF123456',
      display_name: 'Test Model Y',
      option_codes: 'AD15,MDL3,PBSB,RENA,BT37,ID3W,RF3G,S3PB,DRLH,DV2W,W39B,APF0,COUS,BC3B,CH07,PC30,FC3P,FG31,GLFR,HL31,HM31,IL31,LTPB,MR31,FM3B,RS3H,SA3P,STCP,SC04,SU3C,T3CA,TW00,TM00,UT3P,WR00,AU3P,APH3,AF00,ZCST,MI00,CDM0',
      color: 'Pearl White Multi-Coat',
      access_type: 'OWNER',
      granular_access: { hide_private: false },
      tokens: ['1234567890123'],
      state: 'online',
      in_service: false,
      id_s: '1234567890123',
      calendar_enabled: true,
      api_version: 42,
      backseat_token: null,
      backseat_token_updated_at: null,
      ble_autopair_enrolled: false,
      command_signing: 'allowed'
    },
    {
      id: 1234567890124,
      user_id: 123456,
      vehicle_id: 1234567890124,
      vin: '5YJSA1E26JF987654',
      display_name: 'Test Model S',
      option_codes: 'MDLS,RENA,TM00,DRLH,PF00,BT37,ID3W,RF3G,S3PB,DRLH,DV2W,W39B,APF0,COUS,BC3R,CH07,PC30,FC3P,FG31,GLFR,HL31,HM31,IL31,LTPB,MR31,FM3U,RS3H,SA3P,STCP,SC04,SU3C,T3CA,TW01,TM00,UT3P,WR00,AU3P,APH4,AF00,ZCST,MI02,CDM0',
      color: 'Midnight Silver Metallic',
      access_type: 'OWNER',
      granular_access: { hide_private: false },
      tokens: ['1234567890124'],
      state: 'asleep',
      in_service: false,
      id_s: '1234567890124',
      calendar_enabled: true,
      api_version: 42,
      backseat_token: null,
      backseat_token_updated_at: null,
      ble_autopair_enrolled: false,
      command_signing: 'allowed'
    }
  ]
};